jsx3.Class.defineClass("jsx3.amp.util.Prefs",null,[jsx3.util.EventDispatcher],function(m,k){var
ub={A:"prefsImage",B:"40 0 0 0",C:'<div style="position:relative;width:95px;text-align:center;">',D:"</div>",E:" before switching?",a:"unload",b:"switch",c:"save",d:"addPane ",e:"zK",f:"P8",g:"controller",h:"0,*",i:"",j:"Save Changes",k:"Save changes made to ",l:" before closing?",m:"Save",n:"Cancel",o:"Don't Save",p:"number",q:"objPane",r:"#FFFF99",s:"block",t:"100%",u:"div",v:"background-image:url(",w:");background-repeat:no-repeat;background-position:center 8px;",x:"0 0 0 0",y:"pointer",z:"1;"};var
Ra=jsx3.amp.util;m.UNLOAD=ub.a;m.SWITCH=ub.b;m.SAVE=ub.c;k.init=function(){this.XX=[];this.a2=null;this.dc=null;this.d9=null;this.lQ=false;};k.getCollapse=function(){return this.lQ;};k.setCollapse=function(a){this.lQ=a;};k.addPane=function(q){(Ra.PrefsPane.PLUGIN.getLog()).debug(ub.d+q);this.XX.push(q);if(this.a2!=null)this.UD(q);q.subscribe(Ra.PrefsPane.SAVED,this,ub.e);q.subscribe(Ra.PrefsPane.DIRTIED,this,ub.f);};k.loadController=function(l){return Ra.PrefsPane.PLUGIN.loadRsrcComponent(ub.g,l,false);};k.renderIn=function(d,c){this.a2=d;this.dc=this.loadController(d);this.dc.getController=(jsx3.$F(function(){return this;})).bind(this);if(this.getCollapse()&&this.XX.length<2){this.dc.setCols(ub.h);(this.dc.getChild(1)).setBorder(ub.i);}for(var
u=0;u<this.XX.length;u++)this.UD(this.XX[u]);this.a2.paintChild(this.dc);if(this.XX.length>0)jsx3.sleep(function(){if(this.dc.getParent()!=null)this.showPane(c||Number(0));},null,this);};k.unload=jsx3.$Y(function(e){var
Ha=(e.args())[0];var
Qa=(jsx3.$F(function(){this.a2.removeChild(this.dc);this.publish({subject:m.UNLOAD});e.done(true);})).bind(this);if(!Ha&&this.d9!=null&&this.d9.isDirty()){var
Ib=this.dc.getAncestorOfType(jsx3.gui.Dialog)||this.dc.getServer();Ib.confirm(ub.j,ub.k+this.d9.getTitle()+ub.l,(jsx3.$F(function(c){c.doClose();(this.d9.save()).when(Qa);})).bind(this),function(d){d.doClose();e.done(false);},ub.m,ub.n,1,function(c){c.doClose();Qa();},ub.o);}else Qa();});k.apply=function(){this.d9.save();};k.save=function(){(this.d9.save()).when((jsx3.$F(this.unload)).bind(this));};k.zK=function(i){var
M=i.target;if(this.d9==M)this.dc.setButtonsEnabled(false);this.publish({subject:m.SAVE,pane:M});};k.P8=function(s){var
La=s.target;if(this.d9==La)this.dc.setButtonsEnabled(s.dirty);};k.showPane=jsx3.$Y(function(d){var
E=(d.args())[0];var
t=(d.args())[1];if(typeof E==ub.p)E=this.XX[E];if(E==null)throw new
jsx3.IllegalArgumentException(ub.q,arguments[0]);if(t)(this._showPane2(E)).when(d,true);else (this.J9()).when((jsx3.$F(function(j){if(j){(this._showPane2(E)).when(d,true);}else d.done(false);})).bind(this));});k._showPane2=jsx3.$Y(function(n){var
pa=(n.args())[0];var
J=this.d9;var
va=this.dc.getContentPane();va.removeChildren();this.dc.setButtonsEnabled(false);if(J!=null)(this.Nv(J)).setBackgroundColor(ub.i,true);(this.Nv(pa)).setBackgroundColor(ub.r,true);this.d9=pa;(pa.K1(va)).when((jsx3.$F(function(){var
Y=pa.getFirstResponder();if(Y!=null)Y.focus();this.publish({subject:m.SWITCH,from:J,to:pa});n.done();})).bind(this));});k.Nv=function(f){return (this.dc.getListPane()).getDescendantOfName(ub.s+f.getTitle(),false,true);};k.UD=function(s){var
cb=this.dc.getListPane();var
jb=new
jsx3.gui.Block(ub.s+s.getTitle(),0,0,ub.t,60);jb.setTagName(ub.u);jb.setBackground(ub.v+s.getImage()+ub.w);jb.setOverflow(jsx3.gui.Block.OVERFLOWHIDDEN);jb.setTextAlign(jsx3.gui.Block.ALIGNCENTER);jb.setTip(s.getDescription());jb.setPadding(ub.x);jb.setCursor(ub.y);jb.setEvent(ub.z,jsx3.gui.Interactive.JSXCLICK);jb.subscribe(jsx3.gui.Interactive.JSXCLICK,this,function(){this.showPane(s);});cb.setChild(jb);var
z=new
jsx3.gui.Block(ub.A,0,0,95,60);z.setTagName(ub.u);z.setPadding(ub.B);z.setText(ub.C+s.getTitle()+ub.D);z.setTextAlign(jsx3.gui.Block.ALIGNCENTER);jb.setChild(z);cb.paintChild(jb);};k.J9=jsx3.$Y(function(d){var
Lb=(d.args())[0];if(this.d9!=null){if(this.d9==Lb){d.done(false);}else if(this.d9.isDirty()){var
Z=this.dc.getAncestorOfType(jsx3.gui.Dialog)||this.dc.getServer();Z.confirm(ub.j,ub.k+this.d9.getTitle()+ub.E,(jsx3.$F(function(f){f.doClose();(this.d9.save()).when(d,true);})).bind(this),function(q){q.doClose();d.done(false);},ub.m,ub.n,1,function(s){s.doClose();d.done(true);},ub.o);}else d.done(true);}else d.done(true);});});jsx3.Class.defineClass("jsx3.amp.util.PrefsPane",null,[jsx3.util.EventDispatcher],function(f,q){var
ub={a:"save",b:"dirtied",c:"label",d:"tip",e:"img",f:"resource",g:"object"};f.SAVED=ub.a;f.DIRTIED=ub.b;q.init=function(a,m){this.DI=a;this.iG=m;this.vJ=false;this.fZ={};};q.getTitle=function(){return this.iG.attr(ub.c);};q.getDescription=function(){return this.iG.attr(ub.d);};q.getImage=function(){return (this.DI.getPlugIn()).resolveURI(this.iG.attr(ub.e));};q.K1=jsx3.$Y(function(j){var
M=(j.args())[0];var
D=(this.DI.getPlugIn()).getResource(this.iG.attr(ub.f));(D.load()).when((jsx3.$F(function(){this.dc=(this.DI.getPlugIn()).loadRsrcComponent(D,M,false);this.dc.getPane=(jsx3.$F(function(){return this;})).bind(this);this.vJ=false;if(this.dc.loadPrefs)this.dc.loadPrefs();M.paintChild(this.dc);j.done();})).bind(this));});q.getUI=function(){return this.dc;};q.getFirstResponder=function(){if(this.dc.getFirstResponder)return this.dc.getFirstResponder();return null;};q.setDirty=function(e){if(this.vJ!=e)this.publish({subject:f.DIRTIED,dirty:e});this.vJ=e;};q.isDirty=function(){return this.vJ;};q.save=jsx3.$Y(function(i){var
ja=this.dc.savePrefs?this.dc.savePrefs():null;if(ja){this.vJ=false;this.publish({subject:f.SAVED});if(typeof ja==ub.g){var
Pa=this.dc.getAncestorOfType(jsx3.gui.Dialog)||this.dc.getServer();Pa.alert(ja.title,ja.message,function(r){r.doClose();i.done();});}else i.done();}else i.done();});q.getProperty=function(l){return this.fZ[l];};q.setProperty=function(g,o){this.fZ[g]=o;};});
